### ISSUE TITLE
Consider banning UPPER_CASE in favor of camelCase

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/eslint-config-hardcore#156]
### Too many edge cases; no consensus on the rule

```js
class FooBarService {}

export default FooBarService;
```

Should `FooBarService` here be named `FOO_BAR_SERVICE` because it's at the top level?

---

```js
const usersResponse = require("./mocks/responses/users.json");

// ...

server.get("/users", (req, res) => {
  res.send(usersResponse);
});
```

Should `usersResponse` be named `USERS_RESPONSE` because it's at the top level?

---

```js
const CONNECTORS = {
  mail: "gmail",
  calendar: "gcalendar",
};

export default CONNECTORS;
```

Should `mail` and `calendar` be named `MAIL` and `CALENDAR` here?

---

```js
const CONNECTORS = {
  google: {
    mail: "gmail",
    calendar: "gcalendar",
  },
  office: {
    mail: "outlookmail",
    calendar: "outlookcalendar",
  },
};

export default CONNECTORS;
```

Should `google` and `office` be named `GOOGLE` and `OFFICE` here? What about nested `mail` and `calendar`?

### It increases maintenance burden and chance of error

```js
const CONNECTORS = {
  MAIL: "mail",
  CALENDER: "calendar"
};
```

We actually had the CALEND**E**R typo in our codebase.

The above is no more than a futile exercise in manually converting camelCase to UPPER_CASE, there is no benefit in that, and there is harm.

### Impossible to enforce

There is [`prefer-module-scope-constants`](https://github.com/Shopify/web-configs/blob/main/packages/eslint-plugin/docs/rules/prefer-module-scope-constants.md), but it is buggy (https://github.com/Shopify/web-configs/issues/192), and it is inconsistent (allows to have camelCase constants at the top of a file).

### It complicates the linting config and impedes existing naming conventions

I did my best to add support for UPPER_CASE:

https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/61be24af268bf88066bc3eec8011ab18755a6145/ts-for-js.json#L131-L134

but it still produces conflicts in some cases:

```js
// Variable name `IS_PRODUCTION` must have one of the following prefixes: is, should, has, can, did, will
const IS_PRODUCTION = process.env.NODE_ENV === "production";
```

Also, it still allows having UPPER_CASE at inner levels (we actually have cases like this in our codebase):

```js
function foo() {
  const FOO_BAR = 123; // no warning
}
```

And, it conflicts with camelCase object properties:

```js
const CONNECTORS = {
  MAIL: "mail", // Property name `MAIL` must match one of the following formats: strictCamelCase
  CALENDAR: "calendar", // Property name `CALENDAR` must match one of the following formats: strictCamelCase
};
```

## Conclusion

The "use UPPER_CASE constants at the top of the files" rule has too many edge cases, has no consensus, increases maintenance burden, increases chance of error, it is impossible to enforce it, and it impedes the ability to enforce existing conventions.

I propose to ban UPPER_CASE in favor of camelCase.

It would be a much simpler rule to follow, and it would make the code more consistent: **always use camelCase**.

**Comment by ryust-ax** [comment]
From a linting perspective I suppose it makes sense.
From a styling perspective it's "obvious" to me where to use ALL_CAPS vs not use it:
* It's never an import
* If used, it's only ever the primary reference (CONNECTORS but not EMAIL from your example ... CONNECTORS.EMAIL doesn't make sense)
* Ideally it's really only for things that won't or shouldn't change: strings or integers primarily; the use as an object or array feels weird.

However, this is an opinion coming from PHP (v5+) and Python and very little Java, all without an eye toward linted stylings.  In super large files, the all caps made it easy to look for values at the top, quasi or real "global" styled use, etc.  From a Javascript short-files perspective, it makes less sense to keep them.

;) My habit feels correct, but that's a pretty nebulous reason when it comes to trying to justify a linting or style decision across an extremely large and complex codebase with many developers.  So sure?

**Comment by EvgenyOrekhov** [comment]
@ryust-ax I used to follow that convention back in PHP days, but PHP has very straightforward concepts for constants (it's either defined with [`define()`](https://www.php.net/manual/en/language.constants.php), or it's a [class constant](https://www.php.net/manual/en/language.oop5.constants.php)). It was very easy to understand and follow the convention. That is absolutely not true for JavaScript.

> I would want any implementation to not try and wind up trying to force environment variable naming conventions.

Environment variables are out of the scope of this proposal. This proposal is about [JavaScript identifiers](https://developer.mozilla.org/en-US/docs/Glossary/Identifier).

**Comment by slavreniuk** [comment]
Looks fine to me
