### ISSUE TITLE
Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by johanbook** [EvgenyOrekhov/eslint-config-hardcore#163]
This seems like a really cool eslint config! I gave it a try on a typescript project with eslint config 

```json
{
  "extends": ["hardcore", "hardcore/fp", "hardcore/node"],
  "overrides": [
    {
      "files": ["*.js"],
      "extends": ["hardcore/ts-for-js"],
      "parserOptions": { "project": "./tsconfig.json" }
    }
  ]
}
```

and get the error
```
/home/pong/utils/src/cookies/cookies.ts
  3:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'
```

I tried with a ts config of `{}` as suggested in readme. 

I am using E6 syntax and want to use the `import/export` syntax. Do you know what has gone wrong here?

**Comment by EvgenyOrekhov** [comment]
The default value for `sourceType` is `script` (see https://eslint.org/docs/user-guide/configuring#specifying-parser-options). If you want to use ES6 modules, you have to set `"sourceType": "module"` in `parserOptions`.

Regarding TypeScript, I have not tried using eslint-config-hardcore with TypeScript, and I have no idea whether it would work or not. And the `hardcore/ts-for-js` config is meant for linting JavaScript projects, not TypeScript projects (it contains only a small subset of rules, specific to JavaScript).

**Comment by EvgenyOrekhov** [comment]
Please let me know if `"sourceType": "module"` fixed your issue.

**Comment by EvgenyOrekhov** [comment]
BTW, I can see that Node.js 14 was promoted to LTS two days ago, which means now we should be able to use ES6 modules both on client side and on server side. I guess I should set `"sourceType": "module"` as default in eslint-config-hardcore then. And also discourage the use of commonjs. Created https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/164.

**Comment by johanbook** [comment]
In which cases would you want to use `eslint-typscript` for regular javascript? 

I tried adding some variations of `parserOptions` but seems to get
```
> eslint `src/**/*.ts`


Oops! Something went wrong! :(

ESLint: 7.12.1

No files matching the pattern "/home/pong//utils" were found.
Please check for typing mistakes in the pattern.
```

Bit unfamiliar to Eslint, do you  know why this might be?

**Comment by EvgenyOrekhov** [comment]
> In which cases would you want to use `eslint-typscript` for regular javascript?

- when you use new ES features, like class properties or optional chaining, and want to run additional checks on those
- when you want to run additional type-aware checks


Here are some useful typescript-eslint rules that work with JavaScript (they all are included in `hardcore/ts-for-js`):

- [`lines-between-class-members`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/lines-between-class-members.md)
- [`require-await`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md)
- [`return-await`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md)
- [`await-thenable`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md)
- [`no-floating-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md)
- [`no-misused-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md)
- [`promise-function-async`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/promise-function-async.md)
- [`no-throw-literal`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-throw-literal.md)
- [`unbound-method`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/unbound-method.md)
- [`prefer-optional-chain`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-optional-chain.md)
- [`naming-convention`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md) - I really like this one, I was able to enforce boolean naming with it (boolean names have to begin with a prefix, like is/has/should)
- and a few other rules

---

> `No files matching the pattern "/home/pong//utils" were found.`

Looks like you are facing a known issue with eslint-plugin-import and its [`import/no-unused-modules`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unused-modules.md) rule, see https://github.com/benmosher/eslint-plugin-import/issues/1645. I guess you should just disable this rule.

Let me know if that helps.

**Comment by EvgenyOrekhov** [comment]
BTW, I noticed you have `"files": ["*.js"]` in your `overrides` section. If you want to lint `*.ts` files, you should change it to `"files": ["*.ts", "*.js"]`.

**Comment by johanbook** [comment]
Aha, I see. With the config 
```json
{
  "extends": ["hardcore", "hardcore/fp", "hardcore/node"],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "script"
  },
  "overrides": [
    {
      "files": ["*.ts"],
      "extends": ["hardcore/ts-for-js"],
      "parserOptions": { "project": "./tsconfig.json" },
      "rules": {"import/no-unused-modules": "off"}
    }
  ]
}
```

```
> eslint 'src/**/*.ts'


Oops! Something went wrong! :(

ESLint: 7.12.1

TypeError: Cannot read property 'node' of undefined
Occurred while linting /home/pong/test-hardcore/src/cookies/index.ts:1
    at /home/pong/test-hardcore/node_modules/eslint-plugin-import/lib/rules/no-namespace.js:28:26
    at Array.find (<anonymous>)
    at ImportNamespaceSpecifier (/home/book/@book/utils-hardcore/node_modules/eslint-plugin-import/lib/rules/no-namespace.js:27:50)
    at /home/book/@book/utils-hardcore/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/book/@book/utils-hardcore/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/book/@book/utils-hardcore/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/book/@book/utils-hardcore/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/home/book/@book/utils-hardcore/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/home/book/@book/utils-hardcore/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
npm ERR! code ELIFECYCLE
```

But then I'll look for another config for typescript :relaxed:

**Comment by EvgenyOrekhov** [comment]
> TypeError: Cannot read property 'node' of undefined

That's unfortunate :( I can see in the stack trace that it's related to the [`import/no-namespace`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-namespace.md) rule. Feel free to report it to eslint-plugin-import's repo.
