### ISSUE TITLE
Definition for rule 'unicorn/no-document-cookie' was not found

### ISSUE THREAD

**Issue by binary64** [EvgenyOrekhov/eslint-config-hardcore#289]
I get lots of these errors:
```
1:1   error  Definition for rule 'unicorn/no-document-cookie' was not found        
```

https://github.com/EvgenyOrekhov/eslint-config-hardcore/search?q=document+cookie shows only 1 hit.

**Comment by EvgenyOrekhov** [comment]
My smoke test would've caught that kind of error. Most probably your dependencies got messed up for some reason, and you ended up with an outdated version of eslint-plugin-unicorn. Try updating your transitive dependencies by running `rm -rf node_modules/ package-lock.json && npm install`.

**Comment by EvgenyOrekhov** [comment]
@binary64 Were you able to resolve the issue?

**Comment by EvgenyOrekhov** [comment]
Unable to reproduce.
