### ISSUE TITLE
Add eslint-plugin-json-format

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/eslint-config-hardcore#30]
https://github.com/bkucera/eslint-plugin-json-format

- [ ] Wait for https://github.com/Bkucera/eslint-plugin-json-format/issues/14
- [ ] Wait for a new release

**Comment by EvgenyOrekhov** [comment]
It's too buggy. It doesn't work with the `json-files` plugin, it gives `Unexpected end of JSON input` for every JSON file, and it gives warnings about skipping files.

**Comment by EvgenyOrekhov** [comment]
I really like the sort-package-json feature, hope the plugin will get better soon. Waiting for https://github.com/Bkucera/eslint-plugin-json-format/issues/14.

**Comment by karlhorky** [comment]
If you use Prettier, I guess one option for sorting `package.json` keys would be https://github.com/matzkoh/prettier-plugin-packagejson

**Comment by EvgenyOrekhov** [comment]
@karlhorky Yeah I use that plugin with Prettier in my projects! Do you think it will automagically work if I add it to **eslint-config-hardcore**'s dependencies? I guess I'll have to try it to know for sure :)

**Comment by karlhorky** [comment]
I'm not sure, I think the plugins are loaded based on entries in `package.json`. However, you could recommend installing this config using `install-peerdeps` or similar and then specify it as a peer dependency... We take this approach with our config: https://github.com/upleveled/eslint-config-upleveled

**Comment by EvgenyOrekhov** [comment]
@karlhorky I tried different options, can't make eslint-plugin-prettier work on `*.json` files :(

**Comment by karlhorky** [comment]
Oh, I don't use `eslint-plugin-prettier` - I'm just using Prettier via the Prettier VS Code extension. But if you want to use that plugin, maybe something with ESLint file extensions or something...

**Comment by EvgenyOrekhov** [comment]
@karlhorky I see. Yeah I wish we could use eslint-plugin-prettier with all Prettier plugins, so we could use ESLint to format any file supported by Prettier.

What's interesting is that I discovered that [@html-eslint/parser](https://github.com/yeonjuan/html-eslint/tree/main/packages/parser) and eslint-plugin-prettier play nicely together, and I managed to set up formatting of `*.html` files with eslint-plugin-prettier :)

https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/5166075ede3738a70c0581cb9cdc1c6dd6486106/base.json#L834

https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/5166075ede3738a70c0581cb9cdc1c6dd6486106/prettier.json#L38-L43

But I couldn't do the same with JSON, unfortunately.

**Comment by RedGuy12** [comment]
Please don’t add eslint-plugin-prettier, the error messages don’t render correctly on Windows machines.

**Comment by EvgenyOrekhov** [comment]
@RedGuy12 eslint-plugin-prettier was added to **eslint-config-hardcore** a long time ago.

**Comment by EvgenyOrekhov** [comment]
This is no longer relevant.

I recommend using Prettier separately from ESLint, with this config:
https://github.com/EvgenyOrekhov/prettier-config
