### ISSUE TITLE
When using ts-for-js, rule "@typescript-eslint/no-floating-promises" conflicts with "no-void"

### ISSUE THREAD

**Issue by alexkramer98** [EvgenyOrekhov/eslint-config-hardcore#321]
Sometimes you want to ignore the result of a promise. When using ts-for-js, the aforementioned rules conflict with each other. 

Acoording to the rule `@typescript-eslint/no-floating-promises` you should either catch, chain (await in this case, as `then` is disallowed by another rule) or `void` the promise.

When I do not want to catch or await the promise, I would use `void` in front of the promise. This usage is blocked by the rule `no-void`.

**Comment by EvgenyOrekhov** [comment]
Thanks! Fixed and released in 19.15.2.
