### ISSUE TITLE
Add eslint-plugin-simple-import-sort

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/eslint-config-hardcore#350]
https://github.com/lydell/eslint-plugin-simple-import-sort

- [x] ~Wait for a new release of eslint-plugin-simple-import-sort?~ There is no new release planned, the plugin seems stable.

**Comment by EvgenyOrekhov** [comment]
Is it worth it?

**Comment by lydell** [comment]
> Wait for a new release of eslint-plugin-simple-import-sort?

There is no new release planned.

**Comment by EvgenyOrekhov** [comment]
@lydell Thanks for the heads-up! Is the project abandoned? Do you recommend to keep using `import/order` rule from eslint-plugin-import?

**Comment by lydell** [comment]
> Is the project abandoned?

No, it’s not abandoned. There’s just nothing to release right now. I suspect there won’t be much to do in the plugin until support for https://github.com/tc39/proposal-import-assertions is needed.
