### ISSUE TITLE
ESLint 8?

### ISSUE THREAD

**Issue by RedGuy12** [EvgenyOrekhov/eslint-config-hardcore#365]
Will this work with ESLint 8 in the future?

**Comment by EvgenyOrekhov** [comment]
I just published eslint-config-hardcore v23.0.0 which has ESLint v8 support. I had to temporarily disable eslint-plugin-sort-class-members and eslint-plugin-decorator-position until they become compatible with ESLint v8 and `@typescript-eslint/eslint-plugin` v5.

Note: ESLint v7 is NOT supported now.

**Comment by RedGuy12** [comment]
Thank you!


________________________________
