### ISSUE TITLE
Issue with dependency: putout

### ISSUE THREAD

**Issue by brunoparga** [EvgenyOrekhov/eslint-config-hardcore#385]
Hi, this is not actually an issue with hardcore, but with a dependency from which hardcore gets many many rules, putout: https://github.com/coderaiser/putout/issues/90 . In short, I can only use hardcore if I disable putout. Would it be okay for you to take a look at that?

**Comment by EvgenyOrekhov** [comment]
@brunoparga I updated all dependencies and released [eslint-config-hardcore 23.3.0](https://github.com/EvgenyOrekhov/eslint-config-hardcore/releases/tag/v23.3.0). Can you try it and see if it works for you?

**Comment by brunoparga** [comment]
Thank you, I did try it but it still did not work. I'll see what I can do in terms of a reproduction repo.

**Comment by EvgenyOrekhov** [comment]
I updated all dependencies once again, released [eslint-config-hardcore 23.3.1](https://github.com/EvgenyOrekhov/eslint-config-hardcore/releases/tag/v23.3.1).

**Comment by EvgenyOrekhov** [comment]
I just tried creating a fresh Create React App TypeScript project, I don't see any errors from Putout:

![image](https://user-images.githubusercontent.com/8045060/143093313-0a8dba84-73b3-48f3-88b1-98b519ffc2fa.png)

**Comment by EvgenyOrekhov** [comment]
I used this example config from `README.md`:

```json
{
  "extends": [
    "hardcore",
    "hardcore/react",
    "hardcore/react-testing-library",
    "hardcore/jest",
    "hardcore/fp",
    "hardcore/ts"
  ],

  "parserOptions": {
    "project": "./tsconfig.json"
  },

  "env": {
    "browser": true
  },

  "overrides": [
    {
      "files": ["server/**/*.ts"],
      "extends": ["hardcore/node"],
      "env": {
        "browser": false
      }
    }
  ]
}
```

**Comment by spa5k** [comment]
yarn lint
Error: Error while loading rule 'putout/putout': Plugin "putout-plugin-apply-shorthand-properties" could not be found!

I'm getting this error while using the hardcore in next js based app - 

```js
module.exports = {
    extends: [
    "next/core-web-vitals",
    "hardcore",
    "hardcore/react",
    "hardcore/react-testing-library",
    "hardcore/jest",
    "hardcore/fp",
    "hardcore/ts",
  ],
  env: {
    browser: true,
  },
  parserOptions: {
    project: "./tsconfig.json",
  },
};
```

**Comment by EvgenyOrekhov** [comment]
@spa5k 

I just tried adding **eslint-config-hardcore** to a fresh Next.js app:

```
npx create-next-app@latest --ts
cd next-ts
yarn add --dev eslint-config-hardcore
```

I used your config, It works fine for me:

![image](https://user-images.githubusercontent.com/8045060/145987156-2dac12ae-f1da-4857-8942-1db4023b20e3.png)

**eslint-config-hardcore** has `@putout/plugin-apply-shorthand-properties` declared in its dependencies:

https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/d90f165d3ca23416f07a16960d02d6324055d11e/package.json#L38

So probably your dependencies got mixed up.

If you could provide steps to reproduce your issue, please do.
Also, please make sure you use the latest version of **eslint-config-hardcore**.

**Comment by spa5k** [comment]
Were you using yarn V3 pnp mode?
It do work on normal mode tho

**Comment by EvgenyOrekhov** [comment]
@spa5k How do I enable this mode?

**Comment by EvgenyOrekhov** [comment]
@spa5k OK so I ran this:

```sh
rm -rf node_modules package-lock.json yarn.lock
yarn --pnp
yarn lint
```

and I got this error:

```text
warn  - Detected next.config.js, no exported configuration found. https://nextjs.org/docs/messages/empty-configuration
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/evgeny/Library/Caches/Yarn/v6/npm-@eslint-eslintrc-1.0.5-33f1b838dbf1f923bfa517e008362b78ddbbf318-integrity/node_modules/@eslint/eslintrc/universal.js
require() of ES modules is not supported.
require() of /Users/evgeny/Library/Caches/Yarn/v6/npm-@eslint-eslintrc-1.0.5-33f1b838dbf1f923bfa517e008362b78ddbbf318-integrity/node_modules/@eslint/eslintrc/universal.js from /Users/evgeny/Library/Caches/Yarn/v6/npm-eslint-8.4.1-d6531bbf3e598dffd7c0c7d35ec52a0b30fdfa2d-integrity/node_modules/eslint/lib/linter/linter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename universal.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/evgeny/Library/Caches/Yarn/v6/npm-@eslint-eslintrc-1.0.5-33f1b838dbf1f923bfa517e008362b78ddbbf318-integrity/node_modules/@eslint/eslintrc/package.json.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have no idea what that means :(

**Comment by spa5k** [comment]
You need to do these steps
1. Delete lock file and node modules
2. Run - yarn set version berry
3. Then yarn lint

**Comment by EvgenyOrekhov** [comment]
@spa5k I got a different error:

```text
Error: Failed to load plugin 'putout' declared in '.eslintrc.json » eslint-config-hardcore » ./base.json': @putout/engine-parser tried to access try-catch, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: try-catch
Required by: @putout/engine-parser@npm:4.9.0 (via /Users/evgeny/Downloads/next-ts/.yarn/cache/@putout-engine-parser-npm-4.9.0-40929d5a11-78a1d5c5c8.zip/node_modules/@putout/engine-parser/lib/)

Require stack:
- /Users/evgeny/Downloads/next-ts/.yarn/cache/@putout-engine-parser-npm-4.9.0-40929d5a11-78a1d5c5c8.zip/node_modules/@putout/engine-parser/lib/second-chance.js
```

Will report the issue to Putout.

**Comment by EvgenyOrekhov** [comment]
Created a more specific bug report: https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/399. Closing this one.
