### ISSUE TITLE
Problem with Putout when using Yarn v3 PNP

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/eslint-config-hardcore#399]
Steps to reproduce:

```sh
npx create-next-app@latest --ts
cd next-ts
yarn add --dev eslint-config-hardcore
# Add hardcore configs to .eslintrc.json
rm -rf node_modules package-lock.json yarn.lock
yarn set version berry
yarn
yarn lint
```

Expected behavior: should run ESLint successfully

Actual behavior: `Error: Error while loading rule 'putout/putout': Plugin "putout-plugin-apply-shorthand-properties" could not be found!`

Moved from https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/385

**Comment by EvgenyOrekhov** [comment]
Created https://github.com/coderaiser/putout/issues/93.

**Comment by EvgenyOrekhov** [comment]
@coderaiser I tried creating a fresh Next.js project and installing **eslint-config-hardcore** (as described [here](https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/399#issue-1080923564)), and got the same error :(

```text
Error: Error while loading rule 'putout/putout': Plugin "putout-plugin-apply-shorthand-properties" could not be found!
```

**Comment by EvgenyOrekhov** [comment]
@coderaiser I tried adding `pnpMode: "loose"`, got a bunch of "MODULE_NOT_FOUND" warnings, but it worked!
Can we make `putout-plugin-apply-shorthand-properties` work without using loose mode?

**Comment by coderaiser** [comment]
It worked, but now I see that it works with `apply-shorthand-properties works good with `putout`, when `.putout.json` updated, but `ESLint` doesn't see it at all, when I update `extends` with `hardcore`.

**Comment by coderaiser** [comment]
No! It works good, take a look:

![image](https://user-images.githubusercontent.com/1573141/146383337-66533eb8-c0cb-437a-a172-b62dca740a26.png)

```sh
coderaiser@localcmd:~/putout-yarn3$ cat .eslintrc.json
{
    "extends": [
        "next/core-web-vitals",
         "hardcore"
    ]
}
```

**Comment by coderaiser** [comment]
Looks like bundle not created for me anymore. As I see `yarn berry` is a very raw and unstable product, I don't know if it worse to waste time on it...

**Comment by EvgenyOrekhov** [comment]
@coderaiser I agree, it's not worth it. We should wait until Yarn v3 becomes stable.

@spa5k We've done what we could. Apparently Yarn v3 is just raw and buggy.

**Workaround: use npm.**

**Comment by spa5k** [comment]
Thanks for the hardwork. 👍
