### ISSUE TITLE
Enforce alphabetical sorting of things

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/eslint-config-hardcore#449]
Or not?

I've never been a fan of alphabetical sorting, but I'm willing to give it a go.

Note: CSS has a [better alternative](http://markdotto.com/2011/11/29/css-property-order/) (implemented in [stylelint-config-recess-order](https://github.com/stormwarning/stylelint-config-recess-order) and included in [@twinscom/stylelint-config](https://github.com/twinscom/stylelint-config)).

- [x] If yes, should sorting be case-insensitive? I'm leaning towards case-insensitive, it should make it easier to scan code.
  - [x] ~Set `"ignoreCase": true` for [`react/sort-prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md)~  [`react/sort-prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md) should be disabled since prop type sorting will be already covered by object key sorting
  - [x] ~Set `"ignoreCase": true` for [`react/sort-default-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-default-props.md)~ [`react/sort-default-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-default-props.md) should be disabled since default prop sorting will be already covered by object key sorting
  - [x] Set `"ignoreCase": true` for [`react/jsx-sort-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md)
  - [x] Set ignore case for Vue.js rules
  - [x] Set ignore case for any other rules
- [ ] [eslint-plugin-sort-keys-fix](https://github.com/leo-buneev/eslint-plugin-sort-keys-fix)
- [ ] [eslint-plugin-sort-destructure-keys](https://github.com/mthadley/eslint-plugin-sort-destructure-keys)
- [ ] [eslint-plugin-sort](https://github.com/mskelton/eslint-plugin-sort)?
- [x] imports ([`alphabetize`](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/order.md#alphabetize-order-ascdescignore-caseinsensitive-truefalse) option)
- [x] exports
- [x] class members ([`"sort": "alphabetical"`](https://github.com/bryanrsmith/eslint-plugin-sort-class-members) option)
- [ ] ~variables?~ [`sort-vars`](https://eslint.org/docs/rules/sort-vars) won't have any effect because it doesn't sort separate statements

This should be released together with https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/453 and https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/350

**Comment by RedGuy12** [comment]
- I like to sort my imports by type (https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/order.md). Unless you are talking about https://eslint.org/docs/rules/sort-imports, that's fine.

- https://eslint.org/docs/rules/sort-vars has problems when variables depend on another defined in the same block:
```js
 const b = 5, a = b + 10;
```
`sort-vars` wants me to reverse the order of `a` and `b`, but that'll throw an error due to `b` not being defined.
