### ISSUE TITLE
eslint-plugin-graphql no longer maintained

### ISSUE THREAD

**Issue by git-chrisp** [EvgenyOrekhov/eslint-config-hardcore#514]
eslint-plugin-graphql is in the process of being deprecated. Hence, I already receive a peer-dependency issue due to using GraphQL v16. Please switch to graphql-eslint.

**Comment by B2o5T** [comment]
It’s seems like hardcore don’t use eslint-plugin-graphql directly, but welcome to use graphql-eslint as I am its maintainer 😉

**Comment by git-chrisp** [comment]
You're right: https://github.com/Shopify/web-configs/issues/327
