### ISSUE TITLE
Split the eslint-config-hardcore package into multiple smaller packages

### ISSUE THREAD

**Issue by cahian** [EvgenyOrekhov/eslint-config-hardcore#548]
When I install the eslint-config-hardcore package, over 900 other dependency packages are installed. From the eslint-config-hardcore package, I'm only using hardcore and hardcore/node configurations. Because I'm only using these two configurations, out of these 900 dependency packages installed, many of them I believe are unnecessary. I think it would be interesting to create multiple smaller packages, each with a configuration, and if the user wants to install all the configurations, leave the main eslint-config-hardcore package depending on all these other smaller packages.

```
eslint-config-hardcore
eslint-config-hardcore-node
eslint-config-hardcore-jest
eslint-config-hardcore-react
eslint-config-hardcore-react-testing-library
eslint-config-hardcore-functional-programming
eslint-config-hardcore-typescript
eslint-config-hardcore-typescript-for-javascript
```

**Comment by EvgenyOrekhov** [comment]
I tried that back in the day (I had a separate [eslint-config-hardcore-fp](https://github.com/EvgenyOrekhov/eslint-config-hardcore-fp) package), and it was a huge maintenance pain.

Using a single package is much easier both from the user perspective and from the maintainer perspective.

Which practical hindrance do you experience having those extra 900 packages? To me, it's only a few more seconds to install, nothing major.

**Comment by EvgenyOrekhov** [comment]
Closing as `wontfix` since that would make it much harder to use and maintain the package.
