### ISSUE TITLE
Add support for Vue 3 and Nuxt 3

### ISSUE THREAD

**Issue by alexkramer98** [EvgenyOrekhov/eslint-config-hardcore#558]
We currently use this beautiful lib with some modifications/additions to make it work with [Vue.js](https://vuejs.org/) 2.x. 

In the near future we will be switching to Vue 3 and thus I expect more modifications to  be necessary to make the linter work.

Would you be willing to accept a PR for Vue (2.x and 3.x) support? If so, I will work on that as soon as I have the time.

**Comment by EvgenyOrekhov** [comment]
Sure, I would be willing to accept a PR, but only for Vue 3.
