### ISSUE TITLE
no-undef-init vs init-declarations using try/catch

### ISSUE THREAD

**Issue by alexkramer98** [EvgenyOrekhov/eslint-config-hardcore#585]
How would you propose assigning data in a try/catch?

For instance:
```ts
let data;

try {
  data = somethingThatCouldGoWrong();
} catch (error) {
  // handle error
}
```

We currently disable ```@typescript-eslint/init-declarations``` to overcome this problem.

Another workaround would be:

```ts
let data = undefined;

try {
  data = somethingThatCouldGoWrong();
} catch (error) {
  // handle error
}
```
But this would mean I need to disable ```no-undef```.

In ```Vue```, for example, the template needs the variable to always be defined before it can reliably be accessed. 

This is an issue I bumped into while working on #577, but it seems too broad to mention there.

**Comment by B2o5T** [comment]
you should always disable `no-undef` for typescript code

https://github.com/typescript-eslint/typescript-eslint/blob/3983d84bb6affc3d14658380491ed74c0692fb0f/packages/eslint-plugin/src/configs/eslint-recommended.ts#L24

**Comment by EvgenyOrekhov** [comment]
@alexkramer98 I think you mean [`no-undef-init`](https://eslint.org/docs/latest/rules/no-undef-init), not [`no-undef`](https://eslint.org/docs/latest/rules/no-undef).

I would declare `data` as a const in the `try` block, and put all code dependent on `data` there:

```js
try {
  const data = somethingThatCouldGoWrong();
  // do something with `data`
} catch (error) {
  // handle error
}
```

As another option, you could provide some meaningful default value:

```js
let data = []; // some default value that makes sense

try {
  data = somethingThatCouldGoWrong();
} catch (error) {
  // handle error
}
```

But I can see that having `undefined` as the default value is a very common use case.
I think the [`init-declarations`](https://eslint.org/docs/latest/rules/init-declarations) rule should be disabled in eslint-config-hardcore.

**Comment by EvgenyOrekhov** [comment]
> you should always disable `no-undef` for typescript code
> 
> https://github.com/typescript-eslint/typescript-eslint/blob/3983d84bb6affc3d14658380491ed74c0692fb0f/packages/eslint-plugin/src/configs/eslint-recommended.ts#L24

`hardcore/ts` extends `plugin:@typescript-eslint/recommended`, so all core rules that should be disabled for TypeScript code are getting disabled.

**Comment by EvgenyOrekhov** [comment]
> I think the [`init-declarations`](https://eslint.org/docs/latest/rules/init-declarations) rule should be disabled in eslint-config-hardcore.

But I really want to discourage people from using `let`.

I'll have to think about it.

@alexkramer98 Please let me know what you think about the first approach I descibed (using `data` as a const in the `try` block).

**Comment by alexkramer98** [comment]
@EvgenyOrekhov I would prefer ```init-declarations``` to be disabled. (Maybe just for ```.vue``` files?).

Unfortunately, your approach of keeping the variable in the scope of the try-block is not possible when that variable needs to be accessible in the template at some point when using the ```composition API``` (which ```Vue 3``` has quite strongly moved towards).

```vue
<template>
<span>My data is: {{ data }}</span>
</template>

<script setup>
try {
  const data = somethingThatCouldGoWrong();
  // do something with `data`
} catch (error) {
  // handle error
}
</script>

<style>
</style>
```

```data``` would not exist in the template.

**Comment by alexkramer98** [comment]
And yes, I confused ```no-undef``` with ```no-undef-init```.

**Comment by EvgenyOrekhov** [comment]
@alexkramer98 I see. Let's disable `init-declarations` and `@typescript-eslint/init-declarations` for `.vue` files in https://github.com/EvgenyOrekhov/eslint-config-hardcore/pull/577.

**Comment by alexkramer98** [comment]
Will do!
