### ISSUE TITLE
Add eslint-plugin-nuxt to `hardcore/vue`

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/eslint-config-hardcore#588]
https://github.com/nuxt/eslint-plugin-nuxt

Note: eslint-plugin-nuxt hasn't had any updates for months, may be abandoned.

**Comment by EvgenyOrekhov** [comment]
@alexkramer98 Pinging you for visibility. PRs are welcome!

**Comment by alexkramer98** [comment]
Maybe we could take a look at adding https://github.com/nuxt/eslint-config instead. 

There has not yet been a response from a team member here: https://github.com/nuxt/eslint-plugin-nuxt/issues/173,
but it looks more complete and active. It is however still under heavy development.

https://github.com/nuxt/eslint-config also solves some issues I've had to fix for https://github.com/EvgenyOrekhov/eslint-config-hardcore/pull/681. These redundant fixes can then be removed from `eslint-config-hardcore`. It also adds some more tweaks I did not think of before.

I do think this might lead to needing to have seperate a config for Nuxt. This could of course extend the existing `hardcore/vue` config.

**Comment by EvgenyOrekhov** [comment]
We can't use `nuxt/eslint-config` because it extends `eslint:recommended` and `@typescript-eslint/eslint-recommended`, which would override rules from `hardcore` and `hardcore/ts`. But we could copy tweaks from `nuxt/eslint-config` to `hardcore/vue`.

I would prefer to have a single `hardcore/vue` config, but if there are significant differences between Vue.js and Nuxt, we could consider creating `hardcore/nuxt` config. I think I would prefer it to be an **additional** config (that doesn't extend `hardcore/vue`), so for a Nuxt project you would need to use `"extends": ["hardcore", "hardcore/ts", "hardcore/vue", "hardcore/nuxt"]`.

**Comment by alexkramer98** [comment]
@EvgenyOrekhov You're right. I overlooked that one. I will try to take a look at this (and https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/589) in the coming weeks.

**Comment by EvgenyOrekhov** [comment]
Note: eslint-plugin-nuxt hasn't had any updates for months, may be abandoned.

**Comment by alexkramer98** [comment]
`eslint-plugin-nuxt` still hasn't had any updates. It might be a better idea to copy some tweaks from https://github.com/nuxt/eslint-config. I will take a look at that this week.

**Comment by EvgenyOrekhov** [comment]
eslint-plugin-nuxt was deprecated.
