### ISSUE TITLE
Add eslint-plugin-vuejs-accessibility to `hardcore/vue`

### ISSUE THREAD

**Issue by EvgenyOrekhov** [EvgenyOrekhov/eslint-config-hardcore#666]
https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility

**Comment by EvgenyOrekhov** [comment]
@alexkramer98 Pinging you for visibility. PRs are welcome!

**Comment by alexkramer98** [comment]
@EvgenyOrekhov I'll have some spare time in January. Will look at these!

**Comment by EvgenyOrekhov** [comment]
@alexkramer98 Released in [eslint-config-hardcore@28.0.0](https://github.com/EvgenyOrekhov/eslint-config-hardcore/releases/tag/v28.0.0). Please let me know if you find any issues.
