### ISSUE TITLE
Add eslint-plugin-unused-imports

### ISSUE THREAD

**Issue by bigpopakap** [EvgenyOrekhov/eslint-config-hardcore#713]
From [this StackOverflow answer](https://stackoverflow.com/a/64463447/21144956), it describes that `unused-imports/no-unused-imports` and `unused-imports/no-unused-vars` are better alternatives to `no-unused-vars` because they include fixers. More information about the package can be found [here on its npm page](https://www.npmjs.com/package/eslint-plugin-unused-imports). It would be really nice to use these rules, to avoid having to manually make the fixes.

For unused imports, I would like to flag them as errors and apply the fixer automatically.

For unused vars, I would like to flag them as errors but NOT apply the fixer, because that could get annoying if you save a file in the middle of writing some code. I think it's fairly likely that a person will save in the middle of writing a function when they haven't yet used the variable, so the auto-fixer could get annoying.

**Comment by EvgenyOrekhov** [comment]
https://github.com/sweepline/eslint-plugin-unused-imports

**Comment by EvgenyOrekhov** [comment]
Released in [v35.4.0](https://github.com/EvgenyOrekhov/eslint-config-hardcore/releases/tag/v35.4.0)
