### ISSUE TITLE
usage with `eslint.config.js`

### ISSUE THREAD

**Issue by laralove143** [EvgenyOrekhov/eslint-config-hardcore#726]
[eslint docs](https://eslint.org/docs/latest/use/configure/configuration-files) say that the [new configuration file](https://eslint.org/docs/latest/use/configure/configuration-files-new) will be used and the [current version](https://eslint.org/docs/latest/use/configure/configuration-files) will be deprecated

im unsure how to use this config with the new file, and the readme doesn't give any examples, it could at least give an example for both

**Comment by EvgenyOrekhov** [comment]
I think all the plugins will need to add support for the new config format first.
