### ISSUE TITLE
Support keeping prettier outside ESLint

### ISSUE THREAD

**Issue by matwilko** [EvgenyOrekhov/eslint-config-hardcore#771]
In my project, I use prettier separately from ESLint, as recommended by the project [Integrating with Linters](https://prettier.io/docs/en/integrating-with-linters.html).

However, `react.json`, `ts.json` both force `prettier.json` to be pulled in as well, and I've had to do a manual patch locally to prevent hardcore from setting it up.

I'd like to suggest improving support for the two main ways of using prettier, that is, either integrated into ESLint or managed separately.

I think the default should be changed to not include `prettier.json` in other configs. This would mean that prettier would stop being run at all unless a user explicitly enabled it. A new config, `hardcore/formatting` could then be introduced to enable `eslint-plugin-prettier` if wanted, but otherwise, formatting is left up to the user.

I realise that would be a breaking change, so a slightly less drastic alternative might be:

Expose a new `hardcore/no-formatting` configuration that turns off everything turned on in `prettier.json` so that users can use an external formatter without the cost of ESLint doing the same job as well.

This option is harder to maintain and messier in terms of configuration in ESLint, but wouldn't be a breaking change.

Additionally, I'd suggest (in both cases), pulling in `eslint-config-prettier` to disable style rules across ESLint and various plugins - I think in both scenarios (built-in/external formatting) this is a good default so that ESLint is consistently not doing any style related linting (except through `prettier`/whatever other formatter).

**Comment by EvgenyOrekhov** [comment]
Disabling Prettier in ESLint should be as easy as adding this to your config:

```json
"rules": {
  "prettier/prettier": "off"
}
```

Or am I missing something?

---

> I'd suggest (in both cases), pulling in `eslint-config-prettier` to disable style rules across ESLint and various plugins

**eslint-config-hardcore** does use eslint-config-prettier, see

https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/8e6d390479d67d429cc7709e2c090e73fb79e0fb/package.json#L49

https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/8e6d390479d67d429cc7709e2c090e73fb79e0fb/prettier.json#L2

**Comment by matwilko** [comment]
> `"prettier/prettier": "off"`

Yep, it's that easy, _if_ you notice that `prettier` is being run, and you spelunk into the configs to realise `eslint-plugin-prettier` is being implicitly included and then figure out how to disable it 😄

> Or am I missing something?

I don't think you're necessarily missing anything in terms of disabling `prettier`, but I think there's a wider perspective to look at this from - that is, while I can disable `eslint-plugin-prettier` using the above _today_, what happens if some time down the line, `hardcore` decides to switch to a different plugin for formatting? Perhaps a new, better version of the prettier plugin comes along, or a better-but-compatible replacement for prettier comes along?

Another downside to the implicit inclusion of `prettier.json` in these other configs is that it's easy to accidentally create a big perf hit, but one that's somewhat invisible - i.e. if I'm _also_ running prettier outside of ESLint, and they're always run together (in say, a `"scripts": { "lint": "..." }`), then a dev won't necessarily notice that prettier is running twice! And especially on a new project where that perf difference is initially minimal, but will become much greater over time, it's important that devs know what their tools are actually doing 😄

I suppose I'm asking for some explicit _intentionality_ from the "API" of `hardcore`, i.e. I want to be able to express "I don't want `hardcore` to configure any formatting of my code for me, I'll do that myself separately." (or the alternate breaking version, where the user has to make an explicit choice to enable formatting by `hardcore`)

While `"prettier/prettier": "off"` accomplishes that today, it's fragile and doesn't express the same thing. An explicit config (that may just wind up turning off that single rule) makes the intention clear, and is compatible with any potential future changes - if `hardcore` changes formatting during a later upgrade, this separate config will also be updated to turn that new system off without me having to intervene or getting errors/perf regressions etc. 😄

> `eslint-config-hardcore` does use `eslint-config-prettier`

Oops, yeah, didn't spot that transitive dependency! I think I was distracted by `rules-disabled-by-prettier.json`, which doesn't actually seem to be referenced anywhere (anymore?).

I suppose this becomes a request then to make that dependency explicit, so all the formatting stuff in ESLint is disabled whether or not `eslint-plugin-prettier` gets configured? e.g. if `extends: ['prettier']` were added to `base.json`, that creates a good baseline for everything else to work from, i.e. no formatting by default unless you layer something on top.

**Comment by EvgenyOrekhov** [comment]
Prettier was removed in [v45.0.0](https://github.com/EvgenyOrekhov/eslint-config-hardcore/releases/tag/v45.0.0).

**eslint-config-hardcore** remains compatible with default Prettier options,
but now it is recommended to run Prettier separately.

I recommend this Prettier config to format as many file types as possible:
https://github.com/EvgenyOrekhov/prettier-config
