### ISSUE TITLE
Excuse me, what tool is the tables in `README.md` automatically generated?

### ISSUE THREAD

**Issue by u3u** [EvgenyOrekhov/eslint-config-hardcore#788]

**Comment by EvgenyOrekhov** [comment]
I maintain tables manually.

**Comment by u3u** [comment]
Wow! Awesome! Great! 😮
This is a quite tedious task, it's hard to imagine that this is manually maintained!

**Comment by EvgenyOrekhov** [comment]
Yeah that's true, It's tedious. And I don't think rule counts are 100% accurate. But it's good enough, I guess.
