### ISSUE TITLE
Is there a way to exclude an entire dependency/rule group?

### ISSUE THREAD

**Issue by Grafluxe** [EvgenyOrekhov/eslint-config-hardcore#79]
Thanks for grouping all these rules together. 

Is it possible to use your collection of rules, but to exclude the use (and/or install) of specific dependency/rule groups? More specifically, is there a way to use your `hardcore` + `hardcore/fp` setting without `eslint-plugin-ramda` and `eslint-plugin-json`?

**Comment by EvgenyOrekhov** [comment]
There is no way to do that right now. The intention is to make it as easy as possible to set up, and enable as many rules as possible by default.

Why do you want to exclude `eslint-plugin-ramda` and `eslint-plugin-json`? Do they interfere with something?

**Comment by Grafluxe** [comment]
I understand and appreciate that you're making it simple to setup. Thanks for the quick response.

As to your question, I wanted to exclude them so to lessen the weight on VSCode (my editor of choice); I have an auto linting setup.

**Comment by EvgenyOrekhov** [comment]
I see, VS Code is also slow for me with this many rules. But I don't think `eslint-plugin-ramda` or `eslint-plugin-json` eat a noticeable amount of resources. `eslint-plugin-json`, for example, won't even run on non-JSON files. `eslint-plugin-import`, on the other hand, can spend **seconds** on analysis. But one should not exclude `eslint-plugin-import`, it's too valuable for any project.
