### ISSUE TITLE
No explicit-function-return-type?

### ISSUE THREAD

**Issue by user72356** [EvgenyOrekhov/eslint-config-hardcore#896]
I'm surprised that this project doesn't activate the https://typescript-eslint.io/rules/explicit-function-return-type/ rule.

I can create functions that return nothing but fail to specify "void" as the return type, and the linter lets me do that.

Am I too hardcore?

**Comment by EvgenyOrekhov** [comment]
> Am I too hardcore?

xD

I would like to maintain some balance between strictness and boilerplateness. I tried using it in one of my small React projects, and it caused too much "noise" in the code. [`explicit-module-boundary-types`](https://typescript-eslint.io/rules/explicit-module-boundary-types/), on the other hand, might be worth it (haven't decided yet, tracked in https://github.com/EvgenyOrekhov/eslint-config-hardcore/issues/738).
