### ISSUE TITLE
Issue with "use client" in next.js project

### ISSUE THREAD

**Issue by user72356** [EvgenyOrekhov/eslint-config-hardcore#897]
The newer (> 13) versions of Next.js allow to render components on the server. Client-only components must add "use client"; at the top of the source code file. 

This appears to be detected as the following errors:

Unused expression statement (remove-unused-expressions)eslint(putout/putout)
Avoid 'use strict' in ESM (strict-mode/remove-useless)eslint(putout/putout)

**Comment by EvgenyOrekhov** [comment]
I need to upgrade Putout, but there's some dependency conflicts.

**Comment by The-Code-Monkey** [comment]
I've also had it where the eslint config is trying to put usememos in my server functions which means I have to eslint disable lines for them

**Comment by EvgenyOrekhov** [comment]
Waiting for https://github.com/coderaiser/putout/issues/211
